### ISSUE TITLE
Unhandled promises exception handler

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-ignitor#1]
_From @benallfree on October 28, 2017 23:8_

Right now we don't output stack traces for unhandled promises.

https://github.com/nodejs/node/issues/9523#issuecomment-259303079

`process.on('unhandledRejection', r => console.log(r))`

Fixes it.

Is this something that is worth adding to the framework when in dev mode?

_Copied from original issue: adonisjs/adonis-framework#688_

**Comment by thetutlage** [comment]
Yes, we can add this. But with a **bold** warning saying that all `async/await` should be wrapped inside try/catch and Promises should have `.catch` on them

**Comment by benallfree** [comment]
Laravel solves this with a global exception handler as last resort. Of course users can wrap in try/catch if they wish, but I hope this handler would keep the process from exiting in production and log the error (or display it?), and in dev mode just output a stack trace like the sample above. What do you think?

**Comment by thetutlage** [comment]
Yeah so in Node land, we prefer the process to crash for uncaught exceptions. So here are 2 things.

1. Uncaught exceptions
2. Unhandled rejections

The first one is something blowed somewhere and no one handled it. So we want the process to crash, so that there are no weird memory leaks. 
https://nodejs.org/docs/latest/api/process.html#process_event_uncaughtexception

----

The unhandled rejections is more of, dude you are writing async code and expecting that it will never reject, but that is wrong.

We should add a listener for it, but only for educating the user that there is something wrong and but not for rescuing them from a bad situation.

**Comment by benallfree** [comment]
That would work for me. Like we run it in dev mode and each time it fires it shows a big warning educating developers about what to do.

To be fair, at dev time, most of my exceptions have to do with buggy code, not actually legitimate runtime exceptions :)

```
WARNING: Adonis has detected an unhandled rejection that will cause node to exit in a live environment. Examine the cause of this rejection. If it might normally occur in a live environment, use try/catch to gracefully handle it. If it is a programming error, correct it now. 
```

**Comment by thetutlage** [comment]
Yes, will do this

**Comment by benallfree** [comment]
Fine work!!
