### ISSUE TITLE
Cannot find module '...', when set aliases in app.js

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-ignitor#12]
Hello friends!

I had bug **Error: Cannot find module '...'**, when used aliases in app.js, which generated in providers

I've analized code
https://github.com/adonisjs/adonis-ignitor/blob/496cdb8eafecbf55bfb6bf60388ed87f913098b6/src/Ignitor/index.js#L757-L767

And I suppose calling _defineAliases must be BEFORE _bootProviders:
```js
    /**
     * Register providers
     */

    this._registerProviders()
    /**
     * Define aliases by reading them from the `start/app.js` file, so that
     * pre-defined aliases are overridden by the user defined aliases.
     */
    this._defineAliases()

    /**
     * Boot providers
     */
    await this._bootProviders()
```

After this bug was solved

**Comment by thetutlage** [comment]
Can you please share the code where you have defined the aliases?

**Comment by yariksav** [comment]
For example, i used module https://github.com/enniel/adonis-acl,
in adonis-acl docs:
3. Setting up aliases inside start/app.js file.
```js
const aliases = {
  ...
  Role: 'Adonis/Acl/Role',
  Permission: 'Adonis/Acl/Permission',
  ...
}
```
and when i use it in start/hooks.js, or in some model (for example app/Models/User.js)
```js
const Role = use('Role')
```

then application throws Error `Cannot find module 'Role'`

**Comment by thetutlage** [comment]
Can you please share the entire at once? I cannot tell anything unless I can see each piece of the problem

**Comment by yariksav** [comment]
file start.app.js
```js
'use strict'

const path = require('path')
/*
|--------------------------------------------------------------------------
| Providers
|--------------------------------------------------------------------------
|
| Providers are building blocks for your Adonis app. Anytime you install
| a new Adonis specific package, chances are you will register the
| provider here.
|
*/
const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/framework/providers/ViewProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/shield/providers/ShieldProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/auth/providers/AuthProvider',
  'adonis-acl/providers/AclProvider',
]

/*
|--------------------------------------------------------------------------
| Ace Providers
|--------------------------------------------------------------------------
|
| Ace providers are required only when running ace commands. For example
| Providers for migrations, tests etc.
|
*/
const aceProviders = [
  '@adonisjs/lucid/providers/MigrationsProvider',
  '@adonisjs/lucid/providers/MigrationsProvider',
  'adonis-acl/providers/CommandsProvider'
]

/*
|--------------------------------------------------------------------------
| Aliases
|--------------------------------------------------------------------------
|
| Aliases are short unique names for IoC container bindings. You are free
| to create your own aliases.
|
| For example:
|   { Route: 'Adonis/Src/Route' }
|
*/
const aliases = {
  Role: 'App/Models/Role',
  Permission: 'Adonis/Acl/Permission'
}

/*
|--------------------------------------------------------------------------
| Commands
|--------------------------------------------------------------------------
|
| Here you store ace commands for your package
|
*/
const commands = [
]

module.exports = { providers, aceProviders, aliases, commands }
```

**Comment by yariksav** [comment]
file app/Models/User.js
```js
'use strict'

const Model = use('Model')
const Role = use('Role')

class User extends Model {
...
}
```

Error: Cannot find module 'Role'
at /Users/yarik/Projects/cmpact/billing-back/app/Models/User.js(anonymous):4
1  'use strict'
2
3  const Model = use('Model')
4  const Role = use('Role')
5
6  class User extends Model {
...

1 requireStack
  /Users/yarik/Projects/cmpact/billing-back/node_modules/require-stack/src/index.js:44

2 Ioc._require
  /Users/yarik/Projects/cmpact/billing-back/node_modules/@adonisjs/fold/src/Ioc/index.js:345

3 Ioc.use
  /Users/yarik/Projects/cmpact/billing-back/node_modules/@adonisjs/fold/src/Ioc/index.js:742

4 requireStack
  /Users/yarik/Projects/cmpact/billing-back/node_modules/require-stack/src/index.js:44

**Comment by thetutlage** [comment]
And where are you using the `User` model?

**Comment by yariksav** [comment]
Everywhere.
Ok, for example, use Role in start/hooks.js also throws Exception

**Comment by thetutlage** [comment]
When I look at the error stack you shared, I cannot see the file from which the `User` model was originated. So I am not sure at what stage of the application, you are requiring the model and it's breaking.

Regarding `start/hooks.js`, again I need to look at the code.

**Comment by yariksav** [comment]
To reproduce this bug:
1) adonis new aliases-test
2) cd aliases-test, npm i adonis-acl
3) put provider and aliases to app.js
```js
'use strict'

/*
|--------------------------------------------------------------------------
| Providers
|--------------------------------------------------------------------------
|
| Providers are building blocks for your Adonis app. Anytime you install
| a new Adonis specific package, chances are you will register the
| provider here.
|
*/
const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/framework/providers/ViewProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/shield/providers/ShieldProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/auth/providers/AuthProvider',
  'adonis-acl/providers/AclProvider'
]

/*
|--------------------------------------------------------------------------
| Ace Providers
|--------------------------------------------------------------------------
|
| Ace providers are required only when running ace commands. For example
| Providers for migrations, tests etc.
|
*/
const aceProviders = [
  '@adonisjs/lucid/providers/MigrationsProvider'
]

/*
|--------------------------------------------------------------------------
| Aliases
|--------------------------------------------------------------------------
|
| Aliases are short unique names for IoC container bindings. You are free
| to create your own aliases.
|
| For example:
|   { Route: 'Adonis/Src/Route' }
|
*/
const aliases = {
  Role: 'Adonis/Acl/Role',
  Permission: 'Adonis/Acl/Permission'
}

/*
|--------------------------------------------------------------------------
| Commands
|--------------------------------------------------------------------------
|
| Here you store ace commands for your package
|
*/
const commands = []

module.exports = { providers, aceProviders, aliases, commands }
```

4. crecte simple start/hooks.js file and use Role

```js
const { hooks } = require('@adonisjs/ignitor')
const Role = use('Role')
```

5. start application adonis serve --dev
![image](https://user-images.githubusercontent.com/2553313/48618296-998d9780-e9a1-11e8-97d1-dee14e98d98f.png)

**Comment by thetutlage** [comment]
I believe it's expected.

The `start/hooks.js` is loaded initially by AdonisJs, so that you can hook into different lifecycle events. At this time the providers are not registered and neither booted.

Simply move your `use` call inside a lifecycle event

```js
hooks.before.httpServer(function () {
  const Role = use('Role')
})
```

**Comment by yariksav** [comment]
Good, before.HttpServer works
but 
```js
hooks.after.providersBooted(() => {
  const Role = use('Role')
})
```
doesn't work

**Comment by yariksav** [comment]
Yes, the problem was when I used aliases in hooks.before|after.providersBooted or in models, which used inside hooks.before|after.providersBooted
If this expected behavior, please make note in [alias documentation](https://adonisjs.com/docs/4.1/ioc-container#_aliases) that 
> aliases will not work in `hooks.before.providersBooted` and `hooks.after.providersBooted`

Thank you, @thetutlage

**Comment by pallavi058** [comment]
Error: Cannot find module '/home/opulence/Project5/app.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
I am getting this error please help me to  solve this project.I dont have much knowledge as I am a fresher in node js.

**Comment by pallavi058** [comment]
Nothing
