### ISSUE TITLE
Cannot find module '@adonisjs/ignitor'

### ISSUE THREAD

**Issue by yasinakcadev** [adonisjs/adonis-ignitor#15]
When I tried to run my application the command line says:
 cannot find the module @adonisjs/ignitor. 
But when I look up the package.json dependecies there is :
 "@adonisjs/ignitor": "^2.0.8" line.
So anyone can please help me about this issue?

**Comment by RomainLanz** [comment]
Hey @yasinakca! 👋 

Have you installed all dependencies?

**Comment by yasinakcadev** [comment]
Yes, I installed all dependencies and it's works fine now. Thank you.
