### ISSUE TITLE
Error: Cannot find module './src/Hooks'

### ISSUE THREAD

**Issue by pirmax** [adonisjs/adonis-ignitor#4]
Hi,

I have an error with adonis/ignitor package, I've installed packages from `npm install` but I've this error in console:

> 0| | Error: Cannot find module './src/Hooks'
> 0| |     at Function.Module._resolveFilename (module.js:536:15)
> 0| o|     at Function.Module._load (module.js:466:25)
> 0| |     at Module.require (module.js:579:17)
> 0| |     at require (internal/module.js:11:18)
> 0| |     at Object.<anonymous> (/home/website/server/releases/xxxxxxx/node_modules/@adonisjs/ignitor/index.js:12:15)
> 0| |     at Module._compile (module.js:635:30)
> 0| |     at Object.Module._extensions..js (module.js:646:10)
> 0| |     at Module.load (module.js:554:32)
> 0| |     at tryModuleLoad (module.js:497:12)
> 0| |     at Function.Module._load (module.js:489:3)

**Comment by RomainLanz** [comment]
Hey @pirmax! 👋 

Could you please tell us exactly what you have done?

**Comment by pirmax** [comment]
I use Buddy Git pipelines to upload my project on production server.

This project is in current folder. Pipeline upload and `npm install --only=production` to install all project.

When the AdonisJS server start, I have this error in console.

**Comment by RomainLanz** [comment]
And does your application works on your machine?

**Comment by thetutlage** [comment]
Kind of weird the `Hooks` directory does exists. Can u please manually verify the existence of `src/Hooks` inside `node_modules/@adonisjs/ignitor` directory?
