### ISSUE TITLE
Server start tries to load factory.js even if .loadCommands() not called

### ISSUE THREAD

**Issue by webdevian** [adonisjs/adonis-ignitor#8]
Introduced in 2.0.0. My server.js file:
```js
const { Ignitor } = require('@adonisjs/ignitor')

new Ignitor(require('@adonisjs/fold'))
  .appRoot(__dirname)
  .fireHttpServer()
  .catch(console.error)
```
Throws the following error:
```
Error: Cannot find module 'Factory'

at /Users/iegner/Code/..../database/factory.js:
`const Factory = use('Factory')`
```

This can be suppressed by adding `.loadCommands()`, but I think this is inconsistent. 
factory.js should not be loaded if Factory isn't already loaded. Should factory.js only be loaded if loadCommands is called?

**Comment by thetutlage** [comment]
`Factory` is always available once `@adonisjs/lucid` is configured and I am not sure why one will create the `factory.js` file without using Lucid?

**Comment by webdevian** [comment]
I'm definitely using Lucid and also need to use the factory file for seeds. This is my dependencies:

```json
    "@adonisjs/ace": "4.0.8",
    "@adonisjs/bodyparser": "2.0.1",
    "@adonisjs/cli": "4.0.0",
    "@adonisjs/fold": "4.0.5",
    "@adonisjs/framework": "5.0.0",
    "@adonisjs/ignitor": "2.0.0",
    "@adonisjs/lucid": "4.1.3",
```

**Comment by webdevian** [comment]
And my providers:

```
const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider'
]
```

**Comment by thetutlage** [comment]
Can u share the `aceProviders` array as well

**Comment by webdevian** [comment]
const aceProviders = [
  '@adonisjs/lucid/providers/MigrationsProvider'
]

I get the same result even when commenting out this provider

**Comment by thetutlage** [comment]
Actually you are right. The error was swallowed earlier due to some bug in this module. I will fix it in lucid instead
